source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'CocoLib_Example' do

pod 'AFNetworking' ,  '~> 3.1.0'
  pod 'CocoLib', :path => '../'

  target 'CocoLib_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
